### ISSUE TITLE
Jester doesn't work with asynchttpserver

### ISSUE THREAD

**Issue by tim-st** [dom96/jester#165]
For the following
```nim
import jester

routes:
  get "/hello/@name":
    resp "Hello " & @"name"
```
the first valid request like `http://127.0.0.1:5000/hello/name`
is answered and directly after this crashes `jester` with something like
```
INFO Jester is making jokes at http://127.0.0.1:5000 (all interfaces)
DEBUG GET /hello/name
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
jesterTest.nim(3)        jesterTest
jester.nim(489)          serve
asyncdispatch.nim(1645)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(353)   runOnce
asyncdispatch.nim(189)   processPendingCallbacks
asyncmacro.nim(47)       processRequest_continue
[[reraised from:
jesterTest.nim(3)        jesterTest
jester.nim(489)          serve
asyncdispatch.nim(1645)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(353)   runOnce
asyncdispatch.nim(189)   processPendingCallbacks
asyncmacro.nim(36)       processClient_continue
asynchttpserver.nim(288) processClientIter
asyncfutures.nim(302)    read
]]
[[reraised from:
jesterTest.nim(3)        jesterTest
jester.nim(489)          serve
asyncdispatch.nim(1645)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(353)   runOnce
asyncdispatch.nim(189)   processPendingCallbacks
asyncfutures.nim(348)    :anonymous
]]
Error: unhandled exception: Async procedure (processRequest) yielded `nil`, are you await'ing a `nil` Future?
Async traceback:
  jesterTest.nim(3)        jesterTest
  jester.nim(489)          serve
  asyncdispatch.nim(1645)  runForever
  asyncdispatch.nim(1514)  poll
    ## Processes asynchronous completion events
  asyncdispatch.nim(353)   runOnce
  asyncdispatch.nim(189)   processPendingCallbacks
    ## Executes pending callbacks
  asyncmacro.nim(47)       processRequest_continue
    ## Resumes an async procedure
  #[
    jesterTest.nim(3)        jesterTest
    jester.nim(489)          serve
    asyncdispatch.nim(1645)  runForever
    asyncdispatch.nim(1514)  poll
      ## Processes asynchronous completion events
    asyncdispatch.nim(353)   runOnce
    asyncdispatch.nim(189)   processPendingCallbacks
      ## Executes pending callbacks
    asyncmacro.nim(36)       processClient_continue
      ## Resumes an async procedure
    asynchttpserver.nim(288) processClientIter
    asyncfutures.nim(302)    read
  ]#
Exception message: Async procedure (processRequest) yielded `nil`, are you await'ing a `nil` Future?
Exception type: [AssertionError]
```
Invalid requests work as expected.
Tested on Nim `Version 0.18.1 [Windows: amd64]; Compiled at 2018-08-26` with `jester@#head`.

**Comment by tim-st** [comment]
Hm, the following works:
```nim
import jester

router api:
  get "/info/@name":
    resp @"name"

routes:
  extend api, "/api"
```

**Comment by dom96** [comment]
Windows-only issue sadly. (or with ``-d:useStdLib``).

**Comment by PrimordialHelios** [comment]
Just to address the

>I tried `-d:useStdLib` too, but the same error appears :\

real quick: What dom means is that if you compile on a non-windows OS with `-d:useStdLib`, the error is reproducible. From what I can tell, Jester seems to have some issues with asynchttpserver, which is used on windows whereas other OS's use HttpBeast.

Hope I cleared that up :)

**Comment by dom96** [comment]
Seems this is a Nim regression and is fixed in devel, can someone confirm? https://github.com/dom96/jester/issues/179#issuecomment-441861301

**Comment by PrimordialHelios** [comment]
Nim 0.19.9 with latest Jester master seems to still have the issue. Compiling the example provided by @tim-st with `-d:useStdLib` and going to `http://127.0.0.1:5000/hello/name` crashes the application.

**Comment by tim-st** [comment]
On my latest build from 24 days ago there is no difference. I can test a newer version once [this](https://travis-ci.org/nim-lang/nightlies/) or [this](https://ci.appveyor.com/project/Araq/nightlies) has one.

**Comment by mpcjanssen** [comment]
Just tried with the current nim master and the error still occurs.
